[project]
name = "SHD"
version = "0.1.0"
description = "Smart Handheld Dumbbell project"
dependencies = [
    "Flask",
    "matplotlib",
    "openai",
    "python-dotenv",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
